/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#396476",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdcbe",
        "outline-variant": "#c1c7cc",
        "on-secondary-container": "#56676c",
        "on-error": "#ffffff",
        "secondary-fixed": "#d4e6eb",
        "surface-container-highest": "#e2e2e4",
        "tertiary-container": "#4f2f0a",
        "surface-variant": "#e2e2e4",
        "on-primary-fixed": "#001f2a",
        "primary-container": "#073b4c",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#a2cde2",
        "surface-bright": "#f9f9fb",
        "background": "#f9f9fb",
        "on-background": "#1a1c1d",
        "outline": "#71787c",
        "secondary-fixed-dim": "#b8cace",
        "inverse-surface": "#2f3132",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#1f4c5d",
        "surface": "#f9f9fb",
        "on-tertiary-fixed-variant": "#623f19",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-fixed": "#2c1600",
        "surface-container": "#edeeef",
        "tertiary-fixed-dim": "#f0bd8c",
        "surface-container-high": "#e8e8e9",
        "tertiary": "#341b00",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#41484b",
        "on-surface": "#1a1c1d",
        "on-secondary-fixed": "#0d1e22",
        "primary-fixed": "#bde9ff",
        "primary": "#002431",
        "secondary": "#506165",
        "on-tertiary-container": "#c59669",
        "on-primary-container": "#7ba5b9",
        "on-error-container": "#93000a",
        "surface-dim": "#d9dadb",
        "on-secondary-fixed-variant": "#39494e",
        "primary-fixed-dim": "#a2cde2",
        "surface-container-low": "#f3f3f5",
        "error-container": "#ffdad6",
        "secondary-container": "#d4e6eb",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-lg": "24px",
        "touch-target-min": "48px",
        "gutter": "16px",
        "stack-md": "16px",
        "unit": "8px",
        "container-margin": "20px",
      },
      fontFamily: {
        sans: ["Manrope", "Inter", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["30px", { lineHeight: "40px", fontWeight: "700" }],
      },
      boxShadow: {
        "elevation-1": "0px 2px 8px rgba(7, 59, 76, 0.05)",
        "elevation-2": "0px 8px 24px rgba(7, 59, 76, 0.10)",
      }
    },
  },
  plugins: [],
}
